POST http://localhost:8080/v1/orders/
Content-Type: application/json

{
  "parcelNumber": "PL123456789",
  "emailReceiver": "test@example.com",
  "receiverCountryCode": "PL",
  "senderCountryCode": "DE",
  "statusCode": 42
}