POST https://ecommerce1233211.onrender.com/v1/orders/
Content-Type: application/json

{
  "parcelNumber": "PL999000111",
  "emailReceiver": "demo@example.com",
  "receiverCountryCode": "PL",
  "senderCountryCode": "FR",
  "statusCode": 10
}