POST http://localhost:8080/v1/orders/
Content-Type: application/json

{
  "parcelNumber": "FAIL-DOCKER-001",
  "emailReceiver": "fail@example.com",
  "receiverCountryCode": "PL",
  "senderCountryCode": "DE",
  "statusCode": 55
}